### ISSUE TITLE
超过一条数据出现ANR 结合CoordinatorLayout，AppBarLayout，CollapsingToolbarLayout

### ISSUE THREAD

**Issue by yubaokang** [Jude95/RollViewPager#12]
以下是布局
<?xml version="1.0" encoding="utf-8"?>

<android.support.design.widget.CoordinatorLayout   xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/coordinatorLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.design.widget.CollapsingToolbarLayout
            android:id="@+id/collapsingToolbarLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:contentScrim="@color/_ffffff_bg"
            app:expandedTitleMarginEnd="64dp"
            app:expandedTitleMarginStart="23dp"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            
            
            
            
            
            
            
            

            <com.jude.rollviewpager.RollPagerView
                android:id="@+id/rollPagerView"
                android:layout_width="match_parent"
                android:layout_height="@dimen/px450"
                app:layout_collapseMode="parallax"
                app:layout_collapseParallaxMultiplier="0.5" />

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolBar"
                style="@style/ClubToolbar"
                android:layout_width="match_parent"
                android:layout_height="@dimen/px88"
                app:layout_collapseMode="pin"
                app:popupTheme="@style/AppTheme.PopupOverlay">

                <RelativeLayout
                    android:id="@+id/layout_topBar"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="@drawable/bg_gray_alpha_gradient">

                    <TextView
                        android:id="@+id/textView_left"
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:layout_alignParentLeft="true"
                        android:layout_alignParentStart="true"
                        android:layout_centerVertical="true"
                        android:background="@drawable/selector_bg_click_color_alpha"
                        android:drawableRight="@mipmap/ic_arrow_down_white"
                        android:gravity="center"
                        android:paddingLeft="@dimen/contentPaddingLeft"
                        android:text="定位"
                        android:textColor="@color/_ffffff_word"
                        android:textSize="@dimen/sp32" />

                    <TextView
                        android:id="@+id/tv_title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_centerHorizontal="true"
                        android:layout_centerVertical="true"
                        android:text="@string/gj"
                        android:textSize="@dimen/sp36" />

                    <ImageView
                        android:id="@+id/imageView_right"
                        android:layout_width="@dimen/statusBarHeight"
                        android:layout_height="match_parent"
                        android:layout_alignParentEnd="true"
                        android:layout_alignParentRight="true"
                        android:layout_centerVertical="true"
                        android:background="@drawable/selector_bg_click_color_alpha"
                        android:contentDescription="@null"
                        android:padding="@dimen/px15"
                        android:src="@mipmap/ic_service_white" />
                </RelativeLayout>
            </android.support.v7.widget.Toolbar>
        </android.support.design.widget.CollapsingToolbarLayout>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabLayout"
            android:layout_width="match_parent"
            android:layout_height="@dimen/px80"
            android:background="@color/_ffffff_bg"
            app:tabIndicatorColor="@color/_ff5722"
            app:tabIndicatorHeight="@dimen/px4"
            app:tabMode="fixed"
            app:tabPaddingStart="@dimen/px20"
            app:tabSelectedTextColor="@color/_ff5722"
            app:tabTextColor="@color/_000000_word" />
    </android.support.design.widget.AppBarLayout>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <android.support.v4.view.ViewPager
            android:id="@+id/viewPager_home"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <ImageView
            android:id="@+id/iv_empty"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            android:layout_centerHorizontal="true"
            android:layout_marginTop="96dp"
            android:background="@mipmap/bg_empty"
            android:contentDescription="@null"
            android:visibility="gone" />
    </RelativeLayout>
</android.support.design.widget.CoordinatorLayout>
------------------------------------------------------------------------------------------
代码
 rollPagerView.setPlayDelay(1000);
        rollPagerView.setAnimationDurtion(500);
        rollPagerView.setAdapter(new TestLoopAdapter(rollPagerView));
 private class TestLoopAdapter extends LoopPagerAdapter {
        private List<HomeWheelDataList> homes;
        private int[] imgs = {
                R.drawable.cache_normal_new,
                R.drawable.cache_normal_new,
                R.drawable.cache_normal_new,
                R.drawable.cache_normal_new,
        };

        public TestLoopAdapter(RollPagerView viewPager) {
            super(viewPager);
        }

        @Override
        public View getView(ViewGroup container, int position) {
            ImageView view = new ImageView(container.getContext());
            view.setScaleType(ImageView.ScaleType.CENTER_CROP);
            view.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
            view.setImageResource(imgs[position]);
            return view;
        }

        @Override
        public int getRealCount() {
            return imgs.length;
        }
    }
----------------------------------------------ANR traces 文件中的一部分------
suspend all histogram:	Sum: 28.329ms 99% C.I. 4us-8345.600us Avg: 191.412us Max: 10203us
DALVIK THREADS (31):
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x7479a3c0 self=0xb4d36500
  | sysTid=20874 nice=-1 cgrp=default sched=0/0 handle=0xb6fb8b34
  | state=R schedstat=( 38664505309 1819560990 7246 ) utm=3783 stm=83 core=3 HZ=100
  | stack=0xbe0f6000-0xbe0f8000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  at android.support.v4.view.PagerAdapter.getPageWidth(PagerAdapter.java:330)
  at android.support.v4.view.ViewPager.calculatePageOffsets(ViewPager.java:1292)
  at android.support.v4.view.ViewPager.populate(ViewPager.java:1165)
  at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
  at android.view.View.measure(View.java:18811)
  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  at android.support.design.widget.CollapsingToolbarLayout.onMeasure(CollapsingToolbarLayout.java:373)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
  at android.support.design.widget.AppBarLayout.onMeasure(AppBarLayout.java:199)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:664)
  at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:731)
  at android.view.View.measure(View.java:18811)
  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1560)
  at android.view.View.measure(View.java:18811)
  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
  at android.view.View.measure(View.java:18811)
  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2120)
  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1236)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1472)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1127)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6038)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
  at android.view.Choreographer.doCallbacks(Choreographer.java:672)
  at android.view.Choreographer.doFrame(Choreographer.java:608)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5438)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by Jude95** [comment]
![](http://7xn814.com1.z0.glb.clouddn.com/Screenshot_20160430-224705.png)

https://github.com/Jude95/EasyRecyclerView 的demo的Collapsing部分。
你说的是这种效果吧？我实现是没有问题的。
很抱歉我不能运行你的这些代码(很多资源没有好麻烦..)。也不太清楚你的这个问题。你可以简化一下程序寻找下具体原因？（为什么没有错误具体类型）
RollViewPager只是1个普通的View。不会因为结合他们使用而出问题。
