### ISSUE TITLE
notifyDataSetChanged会崩

### ISSUE THREAD

**Issue by maplejaw** [Jude95/RollViewPager#14]
比如说，刚开始的广告有4页，刷新后只有1页时.只要上次的广告停留的不是第一页，刷新后不仅图片没有刷新，而且必崩。提示信息如下
```java
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 4, found: 1 Pager id: com.zhipu.salehelper.referee:id/viewpager_inner Pager class: class android.support.v4.view.ViewPager Problematic adapter: class com.zhipu.salehelper.referee.adapter.HomeLooperAdapter
                                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1000)
                                                                                  at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
                                                                                  at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
                                                                                  at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
                                                                                  at com.zhipu.salehelper.referee.widget.rollviewpager.RollPagerView$TimeTaskHandler.handleMessage(RollPagerView.java:133)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5549)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

可以看出`  at com.zhipu.salehelper.referee.widget.rollviewpager.RollPagerView$TimeTaskHandler.handleMessage(RollPagerView.java:133)`这一行崩的。
刷新代码如下
```java
bannerList.clear();
bannerList.addAll(list);
mLooperAdapter.notifyDataSetChanged();
```

**Comment by Jude95** [comment]
贴一下你的Adapter代码？我测试很正常。

**Comment by maplejaw** [comment]
我刚刚在我fork的代码里，写了个demo。还是有这个问题。
而且还发现，只有切换为一张图片时，居然发生了ANR。
你跑跑试试，不知道是不是我使用的姿势不对。
`git@github.com:maplejaw/RollViewPager.git`

**Comment by Jude95** [comment]
确实是LoopPagerAdapter的BUG。已解决。试试1.3.1。看看还有问题没

ANR的原因真是...找了半天，发现是我的循环是用MAX_INT的页数实现的，一开始就设当前页为MAX_INT/2，1张的时候页数也变为1.(因为某个用户提issue说1页的时候不让左右滑)
于是ViewPager就从MAX_INT/2跑回到第1页.路程太长根本停不下来~~
对于解决办法，我只有这样解决了。重置ViewPager。

    @Override
    public void notifyDataSetChanged() {
        mViewList.clear();
        mViewPager.getViewPager().setAdapter(this);
        super.notifyDataSetChanged();
    }
