### ISSUE TITLE
大神我使用这个轮播图会导致项目崩溃是什么原因NullPointerException异常

### ISSUE THREAD

**Issue by 1123248526** [Jude95/RollViewPager#55]
Process: com.haoontech.jiuducaijing, PID: 12847
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.view.ViewPager com.jude.rollviewpager.RollPagerView.getViewPager()' on a null object reference 
at com.jude.rollviewpager.RollPagerView$TimeTaskHandler.handleMessage(RollPagerView.java:146)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5682)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by hellobenji** [comment]
我用过 但是没有出错。是不是那个地方自己写的代码逻辑有问题了

**Comment by dongxingrong** [comment]
mHandle里获取弱引用有机会拿到空对象;
